language: cpp
compiler:
  - clang

# Setup different environments to test
env:

# Setup repos etc before installation
before_install:
  - sudo add-apt-repository -y ppa:h-rayflood/llvm
  - sudo apt-get update -qq

# Install dependencies
install:
  # install clang
  - sudo apt-get install --allow-unauthenticated -qq clang cmake libboost-all-dev libopencv-dev

# command to run tests
script: 
  - make test

