language: cpp
compiler:
  - clang

# Setup different environments to test
env:
  - CPP14=0
  - CPP14=1

# Setup repos etc before installation
before_install:
  - sudo add-apt-repository -y ppa:h-rayflood/llvm
  - sudo apt-get update -qq

# Install dependencies
install:
  # install clang-3.4 if CPP14==1
  - sudo apt-get install --allow-unauthenticated -qq clang cmake

# command to run tests
script: 
  - make

